config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  devise_for :users, only: [:omniauth_callbacks, :session], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated :user do
    #TODO: configure for production later
    mount Sidekiq::Web => '/sidekiq' if Rails.env.development?

    resources :stared_repos, only: [:index, :update, :show] do
      collection do
        get :tag_list
        put :sync
      end
    end

    root 'stared_repos#index', as: :user_root
  end

  root 'home#index'
end

app/models/stared_repo.rb
class StaredRepo < ActiveRecord::Base
  ## Constants
  REMOTE_ATTRS = %i(name full_name description homepage ssh_url html_url stargazers_count pushed_at)

  ## Third-party extension
  acts_as_taggable_on :tags

  ## Associations
  belongs_to :user

  ## Validations
  with_options presence: true do |pt|
    pt.validates :user_id
    pt.validates :name
    pt.validates :full_name, format: { with: /.*\/.*/ }, uniqueness: { scope: :user_id }
  end

  ## Callbacks
  before_create :parse_readme_html

  ## Attributes
  attr_accessor :user_tag_list

  ## Class methods
  class << self
    def create_from_remote data
      self.where(remote_id: data[:id]).first_or_initialize.tap do |repo|
        repo.assign_attributes data.to_h.slice(*REMOTE_ATTRS)
        repo.first_commit_at = data[:created_at]
        repo.starred_at = data[:updated_at]
        repo.save
      end
    end
  end


  ## Instance methods
  def user_tag_list
    self.tags.map(&:name).join(', ')
  end

  def user_tag_list= value
    self.user.tag(self, with: value, on: :tags)
  end

  private
    def parse_readme_html
      self.readme_html = Octokit::Client.new.readme(self.full_name, accept: 'application/vnd.github.v3.html')
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  ## Third-party extension
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
    :validatable, :omniauthable, omniauth_providers: %i(github)
  acts_as_tagger

  ## Associations
  has_many :stared_repos, dependent: :destroy

  ## Validations
  with_options presence: true do |pt|
    pt.validates :name
    pt.with_options uniqueness: true do |ut|
      ut.validates :github_username
      ut.validates :github_uid
    end
  end

  ## Callbacks
  after_create :start_sync_job


  ## Class methods
  class << self
    def from_omniauth auth
      provider = auth[:provider]

      self.find_or_create_by("#{provider}_uid" => auth[:uid]) do |user|
        user["#{provider}_username"] = auth.info.nickname
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
      end
    end
  end


  ## Instance methods
  def current_sync_job?
    Sidekiq::Status::status(self.sync_job_id).in?(%i[queued working])
  end

  def start_sync_job
    self.update_column :sync_job_id, RepoSyncWorker.perform_async(self.id) unless current_sync_job?
  end

  def sync_stared_repos
    remote_repos = Octokit::Client.new.starred(self.github_username)
    remote_repos.each{ |data| self.stared_repos.create_from_remote(data) }
    self.stared_repos.where.not(remote_id: remote_repos.map{ |attrs| attrs[:id] }).destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stared_repos_controller.rb
class StaredReposController < ApplicationController

  respond_to :json

  def index
    @stared_repos = current_user.stared_repos.includes(:tags)
  end

  def update
    @stared_repo = current_user.stared_repos.find(params[:id])
    @stared_repo.update(params.require(:stared_repo).permit(:user_tag_list))
    render nothing: true
  end

  def show
    @stared_repo = StaredRepo.find(params[:id])
  end

  def sync
    current_user.start_sync_job
    render nothing: true
  end

  def tag_list
    render json: current_user.owned_tags.where("name LIKE '%#{params[:term]}%'").map(&:name)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message :notice, :success, kind: "Github" if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      #TODO: redirect to sign_up instead and pre fill form
      redirect_to root_path
    end
  end

  #TODO: implement, github does not have cancel authorization button
  def failure

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def js_routes
    {
      tags_autocomplete_path: tag_list_stared_repos_path,
      stared_repos_path: stared_repos_path
    }
  end
end

app/views/home/index.html.haml
= content_for :title do
  %h1 Home page

app/views/layouts/_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top{ role: :navigation }
  .container
    .navbar-header
      = link_to 'Dashboard', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li.user-name= current_user.name
        %li= link_to 'Logout', destroy_user_session_path, data: { method: :delete }, class: 'btn btn-link'
      - else
        %li= link_to "Github Auth", user_omniauth_authorize_path(:github), class: 'btn btn-link'

app/views/layouts/application.html.haml
%html{"ng-app"=>"Organizer"}
  %head
    %title Github star organizer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{ id: [controller_name, action_name].join('-') }
    = render 'layouts/header'
    .header-spacer
    = yield
    #js-routes-helper{ data: js_routes }

app/views/stared_repos/_stared_repo.html.haml
%li.list-group-item.row
  .col-xs-2
    = link_to stared_repo.name, stared_repo.html_url, target: :'_blank'
  .col-xs-4
    = stared_repo.description
  .col-xs-5
    = form_for stared_repo, data: { remote: true } do |f|
      = f.text_field :user_tag_list, class: 'repo-tags'
  .col-xs-1
    %span.badge
      %span.glyphicon.glyphicon-star
      = stared_repo.stargazers_count

app/views/stared_repos/index.html.haml
.container{"ng-view"=>""}
-#.container{"ng-controller"=>"MainController"}
-#  %h1
-#    Starred repositories
-#    = link_to sync_stared_repos_path, data: { remote: true, method: :put }, class: 'sync-button' do
-#      %span.glyphicon.glyphicon-refresh
-#        {{my}}
-#
-#  %ul#stared-repos.list-group
-#    = render @stared_repos